channels:
  - cdat-forge
  - conda-forge
dependencies:
  - python>=3
  - sphinx>=1.3.6
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - numpy
  - scipy
  - matplotlib>=1.5
  - ipykernel
  - pandoc
  - ffmpeg
  - pip:
    - nbsphinx
