channels:
  - conda-forge
dependencies:
  - python==3.5
  - sphinx>=1.3.6
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - numpy
  - scipy
  - matplotlib>=1.5
  - ipykernel
  - pandoc
  - pip:
    - nbsphinx
